### ISSUE TITLE
Support import of existing buckets

### ISSUE THREAD

**Issue by bakito** [vshn/provider-minio#48]
### Summary

**As** Cluster Admin\
**I want** a feature\
**So that** I can import existing buckets(resources) into a crossplane resource

### Context

According to crossplane documentation it should be possible to import existing resources. https://docs.crossplane.io/latest/guides/import-existing-resources/

When creating a bucket with the required annotation `crossplane.io/external-name` currently the bucket fails to sync with the error ``

Bucket spec:
```yaml
apiVersion: minio.crossplane.io/v1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: bucket-local-dev
  name: bucket-local-dev
spec:
  deletionPolicy: Delete
  forProvider: {}
  managementPolicies:
    - '*'
  providerConfigRef:
    name: provider-config
```

Error Message:  **"observe failed: bucket already exists, try changing bucket name: bucket-local-dev"**

Versions:
- crossplane: 1.16.0
- provider-minio:  v0.4.0
- k8s: 1.29
